// Code generated by "stringer -type=Action"; DO NOT EDIT.

package player

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PLAY-0]
	_ = x[PAUSE-1]
	_ = x[RESUME-2]
	_ = x[SKIP-3]
	_ = x[DISCONNECT-4]
	_ = x[INSPECT-5]
}

const _Action_name = "PLAYPAUSERESUMESKIPDISCONNECTINSPECT"

var _Action_index = [...]uint8{0, 4, 9, 15, 19, 29, 36}

func (i Action) String() string {
	if i < 0 || i >= Action(len(_Action_index)-1) {
		return "Action(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Action_name[_Action_index[i]:_Action_index[i+1]]
}
